name: check server
on:
  # do at 00:00 everyday
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    # browser + cypress image
    container:
      image: cypress/included:4.9.0
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: 'master'
      - name: run test
        env:
          CYPRESS_CHECK_URL: ${{ secrets.CHECK_URL }}
          CYPRESS_CHECK_TITLE: ${{ secrets.CHECK_TITLE }}
          CYPRESS_CHECK_CSS_ELEMENT: ${{ secrets.CHECK_CSS_ELEMENT }}
        run: npx cypress run --browser chrome
      # screenshot of failure
      # do only when the previous step of a job failed
      - name: get screenshot on failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: check-failure-screenshots
          path: [cypress/screenshots, cypress/videos/]
      # notify to Slack
      - name: notify to slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'check server'
          mention: 'channel'
          mention_if: 'failure'
          channel: '#webhook-action'
          icon_emoji: ':github:'
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
